### ISSUE TITLE
About Robo3D and RoboBEV

### ISSUE THREAD

**Issue by qzhang852** [ldkong1205/Robo3D#4]
Dear authors,
Thank you for your outstanding work. I noticed that your group also has a project named RoboBEV. Are there any plans in the future to couple the two projects, creating a robust benchmark for multi-modal object detection?

**Comment by ldkong1205** [comment]
Hi @qzhang852, thanks for your interest in our works!

Regarding your question: Yes, we have a plan to build the multi-modal robustness benchmark for 3D perception. Two issues are to be tackled:
- Compared to that of the LiDAR-only methods, the number of multi-modal algorithms is limited, especially for 3D semantic segmentation.
- Currently, we are only able to benchmark corruption types related to sensor failure and data processing; for the weather and lighting related corruptions, since the simulation tools for generating the 2D and 3D corruptions are not aligned, it is hard to create scene consistency between the camera views and LiDAR point cloud.

We will try to involve existing open-source multi-modal 3D perception algorithms in our next update (issue 1), and will seek potential solutions for simulating consistent corruptions between 2D and 3D (issue 2).

**Comment by qzhang852** [comment]
Thank you for your swift response, I'm eager to see your future work
