### ISSUE TITLE
About the severity level of fog 

### ISSUE THREAD

**Issue by qzhang852** [ldkong1205/Robo3D#6]
Dear authors,
Thank you for your excellenet work. I found that you pick the back-scattering coefficient to split severity levels. While for other methods, they trend to use  attenuation coefficient to split separted severity levels. Could you please tell me why you choose beta instead of alpha? Thank you in advance.

**Comment by youquanl** [comment]
Hi @qzhang852, Thank you for your question regarding our use of the back-scattering coefficient (β) for defining fog severity levels in our methodology, as opposed to using the attenuation coefficient (α) commonly employed by other methods.

Our choice to utilize β stems from practical considerations and the approach adopted by previous studies. Inspired by "Hahner, et al., Fog Simulation on Real LiDAR Point Clouds for 3D Object Detection in Adverse Weather, ICCV 2021", where α is uniformly sampled from [0, 0.005, 0.01, 0.02, 0.03, 0.06], we found that using α to define fog severity levels might introduce inconsistency due to its random nature. To ensure a more controlled and consistent approach, we opted for β, a manually set parameter during simulation.

Using β allowed us to regulate fog severity levels in a controlled and interpretable manner by modulating the magnitude of the  i<sub>soft</sub> component. This contributed to the stability and reliability of our results, enhancing the experiment's reproducibility.

We observed a similar trend in recent research, such as "Xu Yan, et al., Benchmarking the Robustness of LiDAR Semantic Segmentation Models, arXiv 2023", where the definition of fog simulation difficulty levels was also based on β.
